In [1]:
import cv2
from os import listdir
from os.path import isfile, join
from tqdm.auto import tqdm
from pycocotools.mask import toBbox
import numpy as np
from PIL import Image
from detectron2.structures import BoxMode

In [2]:
folder_images_path = '/home/mcv/datasets/KITTI-MOTS/training/image_02/'
folder_label_path = '/home/mcv/datasets/KITTI-MOTS/instances/'

In [7]:
for f, folder in tqdm(enumerate(listdir(folder_images_path))):
    print("--------------------------")
    images_path = join(folder_images_path, folder)
    onlyimages = [ima for ima in listdir(images_path) if isfile(join(images_path, ima))]
    for i, image in enumerate(onlyimages):
        image_path = folder_images_path + folder + "/" + image 
        label_path = folder_label_path + folder + "/" + image
        
        label = np.asarray(Image.open(label_path))
        height,width = label.shape[:]

        record = {}
        record["file_name"] = image_path
        record["image_id"] = f + i
        record["height"] = height
        record["width"] = width
        patterns = list(np.unique(label))[1:-1]
        objs = []
        for pattern in patterns:
            category_id = int(str(pattern)[0])-1 #Class ids in KITTI-MOTS: (car:1) (pedestrian:2)
            mask_coord = np.argwhere(label==pattern)
            x0, y0 = mask_coord.min(axis=0)    
            x1, y1 = mask_coord.max(axis=0)
            print("XYXY: ", x0,y0,x1,y1)
            bbox = [y0, x0, y1, x1]
            obj = {
                "bbox": bbox,
                "bbox_mode":BoxMode.XYXY_ABS,
                "category_id": category_id,
                "iscrowd": 0
            }
            objs.append(obj)
        record["annotations"] = objs
        print(record)


--------------------------
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


ValueError: not enough values to unpack (expected 2, got 1)

In [ ]:
image_path = '/home/mcv/datasets/KITTI-MOTS/training/image_02/0000/000000.png'
label_path = '/home/mcv/datasets/KITTI-MOTS/instances/0000/000000.png'
label = np.asarray(Image.open(label_path))
height,width = label.shape[:]
print(label.shape[:])
record = {}
record["file_name"] = image_path
record["image_id"] = 
record["height"] = height
record["width"] = width

patterns = list(np.unique(label))[1:-1]
objs = []
for pattern in patterns:
    coord = np.argwhere(label==pattern)
    x0, y0 = coord.min(axis=0)    
    x1, y1 = coord.max(axis=0)
    print(x0,y0)
    print(x1,y1)
    bbox = [y0, x0, y1, x1]
    obj = {
        "bbox": bbox,
        "bbox_mode":BoxMode.XYXY_ABS,
        "category_id": int(np.floor(label[coord[0][0]][label[0][1]]/1e3)-1),
        "iscrowd": 0
    }
objs.append(obj)
record["annotations"] = objs

# TRYING COCOTOOLS

In [ ]:
list(np.unique(label))

In [ ]:
with open(txt_path) as t:
    lines = t.readlines()
    #print(lines)
    bb = toBbox(lines)
    '''lines = t.readlines()
    for line in lines:
        print(line)
        print("--------------------------------------")
        if(line[-1]=="\n"):
            line_splitted = line[:-1].split(' ')
        else:
            line_splitted = line.split(' ')
        print(line_splitted)
        rleObjs = line_splitted[5]
        print(rleObjs)
        bb = toBbox(line_splitted)
        break'''